# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest
# include:
# - template: Security/SAST.gitlab-ci.yml
# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching

# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

# before_script:
#   - python -V  # Print out python version for debugging
#   - pip install virtualenv
#   - virtualenv venv
#   - source venv/bin/activate
#   - pip install -r requirements.txt

# test:
#   script:
#     - pip install pytest
#     - python -m pytest
# #     # - pip install tox flake8  # you can also use tox
# #     # - tox -e py36,flake8
#     - pip install pylint
#     - pylint --fail-under=8.5 --disable=missing-docstring --disable=invalid-name --disable=no-name-in-module --disable=import-error src/

# run:
#   script:
#     - python setup.py bdist_wheel
#     # an alternative approach is to install and run:
#     - pip install dist/*
#     # run the command here
#   artifacts:
#     paths:
#       - dist/*.whl
#
#
# sast:
#   stage: test



## Google cloud
services:
  - docker:dind
variables:
  DOCKER_DRIVER: overlay
stages:
  - update_mirror
google_source:
  image: google/cloud-sdk
  stage: update_mirror
  script:
  - echo "$GOOGLE_KEY" > key.json
  - gcloud auth activate-service-account --key-file key.json
  - git config --global credential.'https://source.developers.google.com'.helper gcloud.sh
  - git remote add google https://source.developers.google.com:2022/p/jelle-streamlit-fantasy-nba/r/g-fantasy-nba
  - git push -f google master
