version: "3.9" # optional since v1.27.0
services:
  python:
    build: .
    container_name: fantasyNBA
    ports:
      - "8501:8501"
    volumes:
      - .:/fantasyNBA

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: nba
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - "6080:8080"
